apiVersion: v1
name: k8s-watcher
description: Watches and sends kubernetes resource-related events
icon: https://raw.githubusercontent.com/komodorio/helm-charts/master/k8s-watcher.svg
version: 1.17.35
appVersion: 1.4.1
